<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNUhafTd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNUhafTd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNUhafTd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNUhafTd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNUhafTd\App_KernelDevDebugContainer([
    'container.build_hash' => 'NUhafTd',
    'container.build_id' => 'fad5b7d9',
    'container.build_time' => 1721884641,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNUhafTd');
