<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLBWGSGt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLBWGSGt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLBWGSGt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLBWGSGt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLBWGSGt\App_KernelDevDebugContainer([
    'container.build_hash' => 'LBWGSGt',
    'container.build_id' => 'fade72de',
    'container.build_time' => 1721908597,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLBWGSGt');
