# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false  # Set services to private by default

    App\infra\Controller\CompanyController:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
        tags: ['controller.service_arguments']    

    App\infra\Repository\database\CompanyRepositoryDatabase:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
        tags:
            - { name: 'doctrine.repository_service' }

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
